import ProductPicker from "../ProductPicker";

function AutoGeneratedTag() {
  return null;
}

export default function NewCampaignProductsSection({
  t,
  loadingProducts,
  availableProducts,
  selectedProducts,
  campaignType,
  errors,
  autoGenerated = false,
  onAddProduct,
  onRemoveProduct,
  onUpdateProduct,
}) {
  return (
    <section
      className={`campaign-form-section ${
        autoGenerated ? "auto-generated-section" : ""
      }`}
    >
      <div className="section-header">
        <div className="field-label-row">
          <h3>{t("form.sections.products")}</h3>
          <AutoGeneratedTag t={t} show={autoGenerated} />
        </div>

        <p>{t("form.sections.productsSubtitle")}</p>
      </div>

      <ProductPicker
        loading={loadingProducts}
        availableProducts={availableProducts}
        selectedProducts={selectedProducts}
        onAddProduct={onAddProduct}
        onRemoveProduct={onRemoveProduct}
        onUpdateProduct={onUpdateProduct}
        campaignType={campaignType}
        errors={errors}
      />
    </section>
  );
}