import { CHANNEL_OPTIONS } from "../../utils";

function AutoGeneratedTag() {
  return null;
}

export default function NewCampaignChannelsSection({
  t,
  formData,
  errors,
  generatedFields = {},
  onToggleChannel,
}) {
  return (
    <section
      className={`campaign-form-section ${
        generatedFields.channels ? "auto-generated-section" : ""
      }`}
    >
      <div className="section-header">
        <div className="field-label-row">
          <h3>{t("form.sections.channels")}</h3>
          <AutoGeneratedTag t={t} show={generatedFields.channels} />
        </div>

        <p>{t("form.sections.channelsSubtitle")}</p>
      </div>

      <div className="channels-wrap">
        {CHANNEL_OPTIONS.map((channel) => {
          const selected = formData.channels.includes(channel);

          return (
            <button
              key={channel}
              type="button"
              className={`channel-chip ${selected ? "active" : ""}`}
              onClick={() => onToggleChannel(channel)}
            >
              {t(`channels.${channel}`)}
            </button>
          );
        })}
      </div>

      {errors.channels ? (
        <p className="field-error">{errors.channels}</p>
      ) : null}
    </section>
  );
}