import { useNavigate } from "react-router-dom";
import { useTranslation } from "react-i18next";

import { Card, PageHeader } from "../../../shared/components";
import { useAuth } from "../../../shared/contexts/AuthContext";

import GenerateCampaignModal from "../components/new-campaign/GenerateCampaignModal";
import NewCampaignChannelsSection from "../components/new-campaign/NewCampaignChannelsSection";
import NewCampaignDetailsSection from "../components/new-campaign/NewCampaignDetailsSection";
import NewCampaignFormActions from "../components/new-campaign/NewCampaignFormActions";
import NewCampaignHeaderActions from "../components/new-campaign/NewCampaignHeaderActions";
import NewCampaignProductsSection from "../components/new-campaign/NewCampaignProductsSection";
import NewCampaignScheduleSection from "../components/new-campaign/NewCampaignScheduleSection";

import { useNewCampaign } from "../hooks/useNewCampaign";

import "./NewCampaign.css";

const NewCampaign = () => {
  const navigate = useNavigate();
  const { t } = useTranslation("campaigns");
  const { hasPermission } = useAuth();

  const canCreate = hasPermission ? hasPermission("campaigns.create") : true;

  const {
    formData,
    availableProducts,
    selectedProducts,
    loadingProducts,
    submitMode,
    pageError,
    successMessage,
    errors,
    createdResult,
    generatedFields,

    generatorModalOpen,
    generatorLoading,
    generatorError,

    campaignEvents,
    eventsLoading,
    eventsError,

    updateField,
    toggleChannel,
    addProduct,
    removeProduct,
    updateSelectedProduct,
    resetForm,
    handleSubmit,

    openGeneratorModal,
    closeGeneratorModal,
    handleGenerateSuggestion,
    loadCampaignEvents,
  } = useNewCampaign(t);

  if (!canCreate) {
    return (
      <div className="new-campaign-page">
        <Card>
          <div className="campaign-permission-state">
            {t("messages.noPermission")}
          </div>
        </Card>
      </div>
    );
  }
const submitAndGoToList = async (mode) => {
  const created = await handleSubmit(mode);

  if (created) {
    navigate("/app/campaigns");
  }
};
  return (
    <div className="new-campaign-page">
      <PageHeader
        actions={
          <NewCampaignHeaderActions
            t={t}
            generating={generatorLoading}
            onGenerate={openGeneratorModal}
            onBack={() => navigate("/app/campaigns")}
          />
        }
      />

      {pageError ? (
        <div className="campaign-page-alert error">{pageError}</div>
      ) : null}

      {successMessage ? (
        <div className="campaign-page-alert success">{successMessage}</div>
      ) : null}

      <Card>
        <div className="campaign-form-shell">
          <NewCampaignDetailsSection
            t={t}
            formData={formData}
            errors={errors}
            generatedFields={generatedFields}
            onUpdateField={updateField}
          />

          <NewCampaignScheduleSection
            t={t}
            formData={formData}
            errors={errors}
            generatedFields={generatedFields}
            onUpdateField={updateField}
          />

          <NewCampaignChannelsSection
            t={t}
            formData={formData}
            errors={errors}
            generatedFields={generatedFields}
            onToggleChannel={toggleChannel}
          />

          <NewCampaignProductsSection
            t={t}
            loadingProducts={loadingProducts}
            availableProducts={availableProducts}
            selectedProducts={selectedProducts}
            campaignType={formData.campaignType}
            errors={errors}
            autoGenerated={generatedFields.products}
            onAddProduct={addProduct}
            onRemoveProduct={removeProduct}
            onUpdateProduct={updateSelectedProduct}
          />

          <NewCampaignFormActions
  t={t}
  submitMode={submitMode}
  createdResult={createdResult}
  generating={generatorLoading}
  onCancel={() => navigate("/app/campaigns")}
  onSubmit={submitAndGoToList}
/>
        </div>
      </Card>

      

      <GenerateCampaignModal
        isOpen={generatorModalOpen}
        loading={generatorLoading}
        error={generatorError}
        startDate={formData.startDate}
        endDate={formData.endDate}
        availableProducts={availableProducts}
        selectedProducts={selectedProducts}
        campaignEvents={campaignEvents}
        eventsLoading={eventsLoading}
        eventsError={eventsError}
        onRefreshEvents={loadCampaignEvents}
        onClose={closeGeneratorModal}
        onGenerate={handleGenerateSuggestion}
      />
    </div>
  );
};

export default NewCampaign;